# Generated by Django 4.0.1 on 2022-04-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_object_options_object_image1_object_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='HeaderImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
