# Generated by Django 4.0.1 on 2022-04-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_category_url_alter_category_headerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.SlugField(null=True),
        ),
    ]
