# Generated by Django 4.0.1 on 2022-04-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_category_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='url',
            new_name='slug',
        ),
    ]
