# Generated by Django 4.0.1 on 2022-04-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_url_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=1)),
                ('imagehome', models.ImageField(blank=True, null=True, upload_to='imagehome/')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Inicio',
            },
        ),
    ]
