# Generated by Django 4.0.1 on 2022-04-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_trip_alter_imagehome_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_trip',
            field=models.DateField(blank=True, null=True),
        ),
    ]
