# Generated by Django 4.0.1 on 2022-04-22 14:24

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_trip_date_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='trips/'),
        ),
    ]
