# Generated by Django 4.0.1 on 2022-04-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_published_alter_equipment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='published',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
